### ISSUE TITLE
Links in PDF

### ISSUE THREAD

**Issue by ramnathv** [jtleek/dataanalysis#3]
I saw a couple of students raise the issue of links not being clickable in the pdf version. I am investigating how to modify the print css so that links are clickable (I am not even sure if it is possible).

In the mean-time a quick fix is to include the following css in `assets/css/custom.css`

``` css
@media print {
  a:after {
   content: " (" attr(href) ")";
   font-size: 10px;
  }
}
```

This would print the link along with the title in the pdf print version so that users can copy-paste the link. This is sub-optimal, but a viable solution at this stage.
